# Generated by Django 5.1 on 2024-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_favorite_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(default='click', max_length=20),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
