# Generated by Django 5.1 on 2024-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_userinteraction_interaction_type_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('click', 'Click'), ('favorite', 'Favorite')], default='click', max_length=20),
        ),
    ]
